version: '3'
services:
  wordpress:
      image: wordpress:latest
      links:
      - db
      environment:
      - WORDPRESS_DB_PASSWORD=password
      - WORDPRESS_DB_USER=root
      ports:
      - "80:80"
      volumes:
      - ./html:/var/www/html
  db:
      image: mysql:latest
      environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=wordpress
      volumes:
      - ./database:/var/lib/mysql